name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Format
        id: format
        run: npm run format-ci
      - name: Lint
        id: lint
        run: npm run lint
      - name: Build website
        id: build
        if: steps.format.outcome == 'success' && steps.lint.outcome == 'success'
        run: npm run build
      - name: Deploy to GitHub Page
        if: steps.build.outcome == 'success'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
